debug: 'FALSE'

default:
  # host: fund-counter.cluster-cmr8sblnu0ix.us-west-2.rds.amazonaws.com
  images:
    name: fund-counter
    subnet: v1
    tag: "2019.10.14.1"
  subnet: v1
  weight: 50

newversion:
  enabled: false
  images:
    name: fund-counter
    tag: "2019.10.14.1"
  subnet: v2
  weight: 50

# slave:
#   host: fund-counter.cluster-ro-cmr8sblnu0ix.us-west-2.rds.amazonaws.com
#   name: fund_counter
