apiVersion: apps/v1
kind: Deployment
metadata:
  name: internal-counter-{{.Values.default.subnet}}
  labels:
    app.kubernetes.io/name: {{.Values.default.images.name}}
    # helm.sh/chart: internal-counter-service-0.1.0
    # app.kubernetes.io/instance: internal-counter.2019.09.24.1
    # app.kubernetes.io/version: "1.0"
    # app.kubernetes.io/managed-by: Tiller
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: {{.Values.default.images.name}}
      # app.kubernetes.io/instance: internal-counter.2019.09.24.1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{.Values.default.images.name}}
        # app.kubernetes.io/instance: internal-counter.2019.09.24.1
    spec:
      containers:
        - name: nginx-proxy
          image: "nginx:1.17.3-alpine"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
            - name: default-config
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: default.conf
            - name: shared-uwsgi-socket
              mountPath: /var/run
          resources:
            {}
            
        - name: {{.Values.default.images.name}}
          image: "651538853910.dkr.ecr.us-west-2.amazonaws.com/internal_counter_service:{{.Values.default.images.tag}}"
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: internal-counter-django-configmap
            - secretRef:
                name: internal-counter-secret
          volumeMounts:
            - name: shared-uwsgi-socket
              mountPath: /var/run
          livenessProbe:
            exec:
              command:
                - uwsgi_curl
                - -H
                - Host:host.name
                - /var/run/internal-counter.sock
                - /health_check
            initialDelaySeconds: 20
            periodSeconds: 20
          readinessProbe:
            exec:
              command:
                - uwsgi_curl
                - -H
                - Host:host.name
                - /var/run/internal-counter.sock
                - /health_check
          resources:
            {}
            
      volumes:
        - name: nginx-config
          configMap:
            name: internal-counter-nginx-configmap
            items:
            - key: nginx.conf
              path: nginx.conf
        - name: default-config
          configMap:
            name: internal-counter-nginx-configmap
            items:
            - key: default.conf
              path: default.conf
        - name: shared-uwsgi-socket
          emptyDir: {}
---
{{ if .Values.newversion.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: internal-counter-{{.Values.newversion.subnet}}
  labels:
    app.kubernetes.io/name: {{.Values.newversion.images.name}}
    # helm.sh/chart: internal-counter-service-0.1.0
    # app.kubernetes.io/instance: internal-counter.2019.09.24.1
    # app.kubernetes.io/version: "1.0"
    # app.kubernetes.io/managed-by: Tiller
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: {{.Values.newversion.images.name}}
      # app.kubernetes.io/instance: internal-counter.2019.09.24.1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{.Values.newversion.images.name}}
        # app.kubernetes.io/instance: internal-counter.2019.09.24.1
    spec:
      containers:
        - name: nginx-proxy
          image: "nginx:1.17.3-alpine"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
            - name: default-config
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: default.conf
            - name: shared-uwsgi-socket
              mountPath: /var/run
          resources:
            {}
            
        - name: {{.Values.newversion.images.name}}
          image: "651538853910.dkr.ecr.us-west-2.amazonaws.com/internal_counter_service:{{.Values.newversion.images.tag}}"
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: internal-counter-django-configmap
            - secretRef:
                name: internal-counter-secret
          volumeMounts:
            - name: shared-uwsgi-socket
              mountPath: /var/run
          livenessProbe:
            exec:
              command:
                - uwsgi_curl
                - -H
                - Host:host.name
                - /var/run/internal-counter.sock
                - /health_check
            initialDelaySeconds: 20
            periodSeconds: 20
          readinessProbe:
            exec:
              command:
                - uwsgi_curl
                - -H
                - Host:host.name
                - /var/run/internal-counter.sock
                - /health_check
          resources:
            {}
            
      volumes:
        - name: nginx-config
          configMap:
            name: internal-counter-nginx-configmap
            items:
            - key: nginx.conf
              path: nginx.conf
        - name: default-config
          configMap:
            name: internal-counter-nginx-configmap
            items:
            - key: default.conf
              path: default.conf
        - name: shared-uwsgi-socket
          emptyDir: {}
{{- end }}