apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: internal-counter-vs
spec:
  gateways:
  - internal-counter-gateway
  hosts:
  - internal-counter.api.pionex.local
  http:
  - route:
    - destination:
        host: internal-counter
        subset: {{.Values.default.subnet}}
        port:
          number: 80
    weight: {{.Values.default.weight}}
    {{- if .Values.newversion.enabled }}
    - destination:
        host: internal-counter
        subset: {{.Values.newversion.subnet}}
        port:
          number: 80
    weight: {{.Values.newversion.weight}}
    {{- end }}
