apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: productpage
spec:
  hosts:
  - "{{.Values.global.appname}}.{{.Values.global.domain}}"
  gateways:
  - {{.Values.global.gatewayname}}
  http:
  - route:
    - destination:
        host: productpage
        subset: v1
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: reviews
spec:
  hosts:
  - reviews
  http:
  - route:
    - destination:
        host: reviews
        subset: {{.Values.review.images.version}}
      weight: {{.Values.review.images.weight}}
    {{- if .Values.preview.enabled }}     
    - destination:
        host: reviews
        subset: {{.Values.preview.images.version}}
      weight: {{.Values.preview.images.weight}} 
    {{- end }}
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: ratings
spec:
  hosts:
  - ratings
  http:
  - route:
    - destination:
        host: ratings
        subset: v1  
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: details
spec:
  hosts:
  - details
  http:
  - route:
    - destination:
        host: details
        subset: v1
---
