apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: reviews-v1
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: reviews
        version: v1
    spec:
      containers:
      - name: reviews
        image: {{.Values.review.images.repository}}-{{.Values.review.images.tag}}
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9080
