apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: reviews-{{.Values.review.images.version}}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: reviews
        version: {{.Values.review.images.version}}
    spec:
      containers:
      - name: reviews
        image: {{.Values.review.images.repository}}-{{.Values.review.images.tag}}
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9080
---
{{- if .Values.preview.enabled -}}
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: reviews-{{.Values.preview.images.version}}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: reviews
        version: {{.Values.preview.images.version}}
    spec:
      containers:
      - name: reviews
        image: {{.Values.preview.images.repository}}-{{.Values.preview.images.tag}}
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9080
{{- end -}}