apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: internal-fund-counter
spec:
  host: internal-fund-counter
  subsets:
  - name: {{.Values.default.subnet}}
    labels:
      version: {{.Values.default.subnet}}      
  {{- if .Values.newversion.enabled }}      
  - name: {{.Values.newversion.subnet}}
    labels:
      version: {{.Values.newversion.subnet}}
  {{- end }}