apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: fund-counter-vs
spec:
  gateways:
  - fund-counter-gateway
  hosts:
  - www.pionex.com
  - www.pionex.co
  http:
  - match:
    - uri:
        prefix: '/fund'
    route:
    - destination:
        host: fund-counter
        subset: {{.Values.default.subnet}}
        port:
          number: 80
      weight: {{.Values.default.weight}}
    {{- if .Values.newversion.enabled }}
    - destination:
        host: fund-counter
        subset: {{.Values.newversion.subnet}}
        port:
          number: 80
      weight: {{.Values.newversion.weight}}
    {{- end }}
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: fund-counter-api-vs
spec:
  gateways:
  - fund-counter-gateway
  hosts:
  - fund.api.pionex.com
  http:
  - route:
    - destination:
        host: fund-counter
        subset: {{.Values.default.subnet}}
        port:
          number: 80
      weight: {{.Values.default.weight}}
    {{- if .Values.newversion.enabled }}
    - destination:
        host: fund-counter
        subset: {{.Values.newversion.subnet}}
        port:
          number: 80
      weight: {{.Values.newversion.weight}}
    {{- end }}
