apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{.Values.appname}}
spec:
  hosts:
  - "{{.Values.appname}}.devops.visionyu.xyz"
  gateways:
  - {{.Values.appname}}-gateway
  http:
  - match:
    - uri:
        exact: /productpage
    - uri:
        prefix: /static
    - uri:
        exact: /login
    - uri:
        exact: /logout
    - uri:
        prefix: /api/v1/products
    route:
    - destination:
        host: productpage
        port:
          number: 9080
